export enum UserActionTypes {
  ADD_USER = '[Users] ADD_USER',
  ADD_USER_SUCCESS = '[Users] ADD_USER_SUCCESS',
  ADD_USER_FAIL = '[Users] ADD_USER_FAIL',
  REFRESH_ADD_USER = '[Users] REFRESH_ADD_USER',

  UPDATE_USER = '[Users] UPDATE_USER',
  UPDATE_USER_SUCCESS = '[Users] UPDATE_USER_SUCCESS',
  UPDATE_USER_FAIL = '[Users] UPDATE_USER_FAIL',
  REFRESH_UPDATE_USER = '[Users] REFRESH_UPDATE_USER',

  DELETE_USER = '[Users] DELETE_USER',
  DELETE_USER_SUCCESS = '[Users] DELETE_USER_SUCCESS',
  DELETE_USER_FAIL = '[Users] DELETE_USER_FAIL',
  REFRESH_DELETE_USER = '[Users] REFRESH_DELETE_USER',

  GET_USERS = '[Users] GET_USERS',
  GET_USERS_SUCCESS = '[Users] GET_USERS_SUCCESS',
  GET_USERS_FAIL = '[Users] GET_USERS_FAIL',
}
